dataColName <- read.table("household_power_consumption.txt",header=FALSE,nrow=1,sep=";",stringsAsFactors=FALSE)
data <- read.table("household_power_consumption.txt",header=FALSE,nrow=2880,sep=";",stringsAsFactors=FALSE,skip=66637)
data$V10 <- as.Date(data[,1],format="%d/%m/%Y")
data$v11 <- strptime(paste(data[,1],data[,2]),format="%d/%m/%Y %H:%M:%S")
par(mfrow=c(1,1))
plot(data[,11],data[,7],col="black",ylab="Energy sub metering",type="l",xlab="")
lines(data[,11],data[,8],col="red")
lines(data[,11],data[,9],col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),col=c("black","red","blue"),lwd=c(2.5,2.5),cex=0.7)
dev.copy(png,"plot3.png")
dev.off()
