dataColName <- read.table("household_power_consumption.txt",header=FALSE,nrow=1,sep=";",stringsAsFactors=FALSE)
data <- read.table("household_power_consumption.txt",header=FALSE,nrow=2880,sep=";",stringsAsFactors=FALSE,skip=66637)
data$V10 <- as.Date(data[,1],format="%d/%m/%Y")
data$v11 <- strptime(paste(data[,1],data[,2]),format="%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
plot(data[,11],data[,3],type="l",xlab="",ylab="Global Active Power",cex.lab=0.7,cex=0.5,cex.axis=0.7)
plot(data[,11],data[,5],xlab="datetime",ylab="Voltage",type="l",cex.lab=0.7,cex.axis=0.7)
plot(data[,11],data[,7],col="black",ylab="Energy sub metering",type="l",xlab="",cex.lab=0.7,cex.axis=0.7)
lines(data[,11],data[,8],col="red")
lines(data[,11],data[,9],col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),col=c("black","red","blue"),lwd=c(2.5,2.5),cex=0.5,bty="n")
plot(data[,11],data[,4],xlab="datetime",ylab="Global_reactive_power",type="l",cex.lab=0.7,cex.axis=0.7)
dev.copy(png,"plot4.png")
dev.off()
