dataColName <- read.table("household_power_consumption.txt",header=FALSE,nrow=1,sep=";",stringsAsFactors=FALSE)
data <- read.table("household_power_consumption.txt",header=FALSE,nrow=2880,sep=";",stringsAsFactors=FALSE,skip=66637)
data$V10 <- as.Date(data[,1],format="%d/%m/%Y")
data$v11 <- strptime(paste(data[,1],data[,2]),format="%d/%m/%Y %H:%M:%S")
par(mfrow=c(1,1))
plot(data[,11],data[,3],ylab="Global Active Power (kilowatts)",type="l",xlab="")
dev.copy(png,"plot2.png")
dev.off()
